### PR TITLE
now using Kevn's bsp.c and bsp.h

### PR DESCRIPTION
**Pull request by lKilgoretrout**
Kevin's new super well commented bsp.c in place of board_io.c.

- It  gate clocks and enables a bunch more GPIO for testing,
-  changes the function names for asserting LEDs a little bit
- tested and it works, try it out yourself!
- board_io.c and board_io.h are now deprecated

### CODE REVIEW

**Comment by Kevin-Ehrichs** [comment]
So I ran into some issues, fixed them, BSP is working, but it appears sleep function is not working as intended on my end. RTOS appears to be cycling through different tasks, but the observation is that the LEDs turn on one color at a time, stay solid for some time (10-20 seconds) then switch to another solid LED color. 

To give context, I re-cloned the repo and switched to this branch then opened up the .eww project file for IAR

**Compilation errors were stating that the project could not find the following files**
  - TM4C123GH6PM.h - this file was brought over from freeRTOS impl. as it is a custom file

The following files were found to be at the following location in my local machine, I suggest we either carry them and all their includes locally in the project or place a disclaimer somewhere stating that these include paths will need to be added prior to compilation
  - core_cm4.h
  - core_cm4.h                          
  - system_TM4C123.h

So all in all, I added the file TM4C123GH6PM.h from freeRTOS repo and added some include paths in the project setup to catch the other 3 files listed above.

In addition to that, I also made a small change to bsp.c/.h as I was facing a warning telling me I was mixing types in the function definition parameters for BSP_setLED()


Upon testing with my latest commit, all LED functionality appears to be working correctly but it takes a very long time for the sleep() function to complete. 

Can someone confirm if this is happening on their end?

**Comment by lKilgoretrout** [comment]
> So I ran into some issues, fixed them, BSP is working, but it appears sleep function is not working as intended on my end. RTOS appears to be cycling through different tasks, but the observation is that the LEDs turn on one color at a time, stay solid for some time (10-20 seconds) then switch to another solid LED color.
> 
> To give context, I re-cloned the repo and switched to this branch then opened up the .eww project file for IAR
> 
> **Compilation errors were stating that the project could not find the following files**
> 
>     * TM4C123GH6PM.h - this file was brought over from freeRTOS impl. as it is a custom file
> 
> 
> The following files were found to be at the following location in my local machine, I suggest we either carry them and all their includes locally in the project or place a disclaimer somewhere stating that these include paths will need to be added prior to compilation
> 
>     * core_cm4.h
> 
>     * core_cm4.h
> 
>     * system_TM4C123.h
> 
> 
> So all in all, I added the file TM4C123GH6PM.h from freeRTOS repo and added some include paths in the project setup to catch the other 3 files listed above.
> 
> In addition to that, I also made a small change to bsp.c/.h as I was facing a warning telling me I was mixing types in the function definition parameters for BSP_setLED()
> 
> Upon testing with my latest commit, all LED functionality appears to be working correctly but it takes a very long time for the sleep() function to complete.
> 
> Can someone confirm if this is happening on their end?

I think the missing files error is that you need to have the qpc folder at the $PROJ_DIR$ (i.e. where your main.c is). You can download it from www.state-machine.com/video-course, any lesson between 20 and 40 has it listed next to it as qpc.zip. 

As far as the sleep function goes, i think it is working as it is supposed to.   Go ahead and modify the program so that it turns on just the red , then sleep(1000) (one second of sleep) andthen turns on the ledred again.

**Comment by Kevin-Ehrichs** [comment]
I see, so in addition to cloning the project, we need to also add the qpc directory to the project / remove it before committing? I assume because this is a large directory?

What I did to test the sleep function was kind of what you mentioned - I set a breakpoint at BSP_setLED(Red, ON), then let it run over sleep(1000) and set another breakpoint after the sleep function. When executing only the sleep function, it takes about 20 seconds to execute the sleep(1000) line.

**Comment by lKilgoretrout** [comment]
correct.
no need to remove qpc from the working dir, just add QPC to the .gitignore
 
 
  On Sat, Feb 18, 2023 at 17:36, ***@***.***> wrote:   


I see, so in addition to cloning the project, we need to also add the qpc directory to the project / remove it before committing? I assume because this is a large directory?

What I did to test the sleep function was kind of what you mentioned - I set a breakpoint at BSP_setLED(Red, ON), then let it run over sleep(1000) and set another breakpoint after the sleep function. When executing only the sleep function, it takes about 20 seconds to execute the sleep(1000) line.

**Pull request merged**
